/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package appdessin;

import appdessin.classes.ColoredCercle;
import appdessin.classes.ColoredLigne;
import appdessin.classes.ColoredRectangle;
import java.awt.Color;
import java.awt.Graphics;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.filechooser.FileSystemView;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Mehdi Fll
 */
public class Fenetre extends javax.swing.JFrame {

    File selectedFile = null;
    String titre;
    String key;
    Lab7cser L;

    public DessinPanel getDessinPanel1() {
        return dessinPanel1;
    }

    public void setDessinPanel1(DessinPanel dessinPanel1) {
        this.dessinPanel1 = dessinPanel1;
    }

    public File getSelectedFile() {
        return selectedFile;
    }

    /**
     * Creates new form appdessin
     */
    public Fenetre() {
        initComponents();

        titre = "AppDessin - Sans nom";
        this.setTitle(titre);
        dessinPanel1.setVisible(false);
        arreterserveur.setVisible(false);
        listeprojets.setVisible(false);
        listeclients.setVisible(false);
        creercompte.setVisible(false);
        //       *.* 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPasswordField1 = new javax.swing.JPasswordField();
        listeprojets = new javax.swing.JButton();
        listeclients = new javax.swing.JButton();
        creercompte = new javax.swing.JButton();
        lancerserveur = new javax.swing.JButton();
        arreterserveur = new javax.swing.JButton();
        dessinPanel1 = new appdessin.DessinPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();

        jPasswordField1.setText("jPasswordField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 600));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        listeprojets.setText("Liste des projets");
        listeprojets.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listeprojetsActionPerformed(evt);
            }
        });
        getContentPane().add(listeprojets, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 130, -1));

        listeclients.setText("Liste des clients");
        listeclients.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listeclientsActionPerformed(evt);
            }
        });
        getContentPane().add(listeclients, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 130, -1));

        creercompte.setText("Créer un compte");
        creercompte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                creercompteActionPerformed(evt);
            }
        });
        getContentPane().add(creercompte, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 130, -1));

        lancerserveur.setText("Lancer le serveur");
        lancerserveur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lancerserveurActionPerformed(evt);
            }
        });
        getContentPane().add(lancerserveur, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 130, -1));

        arreterserveur.setText("Arrêter le serveur ");
        arreterserveur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                arreterserveurActionPerformed(evt);
            }
        });
        getContentPane().add(arreterserveur, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 130, -1));

        javax.swing.GroupLayout dessinPanel1Layout = new javax.swing.GroupLayout(dessinPanel1);
        dessinPanel1.setLayout(dessinPanel1Layout);
        dessinPanel1Layout.setHorizontalGroup(
            dessinPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 730, Short.MAX_VALUE)
        );
        dessinPanel1Layout.setVerticalGroup(
            dessinPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 510, Short.MAX_VALUE)
        );

        getContentPane().add(dessinPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 0, 730, 510));

        jMenuBar1.setBackground(new java.awt.Color(255, 255, 255));

        jMenu2.setText("A propos");
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu2MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu2);

        jMenu3.setText("Services");

        jMenuItem5.setText("Start server");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem5);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing


    }//GEN-LAST:event_formWindowClosing

    private void jMenu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MouseClicked
        Object[] options = {"OK"};
        int n = JOptionPane.showOptionDialog(this,
                "Cette application a été créée par \n"
                + "Mehdi Felloul et Wiam Gharbi ", "A Propos ",
                JOptionPane.PLAIN_MESSAGE,
                JOptionPane.QUESTION_MESSAGE,
                null,
                options,
                options[0]);        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu2MouseClicked

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed


    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void listeprojetsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listeprojetsActionPerformed
        AffichageProjet ap = new AffichageProjet(this);
        ap.setVisible(true);
        getDessinPanel1().setVisible(false);
       // getDessinPanel1().affichage(null, this);
        //dessinPanel1.setVisible(true);

    }//GEN-LAST:event_listeprojetsActionPerformed

    private void lancerserveurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lancerserveurActionPerformed
        L= new Lab7cser();
        new ThreadF(this, L);

        arreterserveur.setVisible(true);
        listeprojets.setVisible(true);
        listeclients.setVisible(true);
        creercompte.setVisible(true);
        lancerserveur.setVisible(false);
    }//GEN-LAST:event_lancerserveurActionPerformed

    private void listeclientsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listeclientsActionPerformed
        dessinPanel1.setVisible(true);
        dessinPanel1.setBackground(dessinPanel1.getParent().getBackground());


    }//GEN-LAST:event_listeclientsActionPerformed

    private void arreterserveurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_arreterserveurActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_arreterserveurActionPerformed

    private void creercompteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_creercompteActionPerformed




        Register Reg = new Register(this);
        Reg.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_creercompteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
//                WebLookAndFeel.install ();
//                WebLookAndFeel.setAllowLinuxTransparency(true);
                /* Set the Nimbus look and feel */
                //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
                /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
                 */
                try {
                    for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                        if ("Windows".equals(info.getName())) {
                            javax.swing.UIManager.setLookAndFeel(info.getClassName());
                            break;
                        }
                    }
                } catch (ClassNotFoundException ex) {
                    java.util.logging.Logger.getLogger(Fenetre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                } catch (InstantiationException ex) {
                    java.util.logging.Logger.getLogger(Fenetre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                } catch (IllegalAccessException ex) {
                    java.util.logging.Logger.getLogger(Fenetre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                } catch (javax.swing.UnsupportedLookAndFeelException ex) {
                    java.util.logging.Logger.getLogger(Fenetre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                }
                //</editor-fold>
                //</editor-fold>

                /* Create and display the form */
                Fenetre F = new Fenetre();
                F.setVisible(true);

            }

        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton arreterserveur;
    private javax.swing.JButton creercompte;
    private appdessin.DessinPanel dessinPanel1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JButton lancerserveur;
    private javax.swing.JButton listeclients;
    private javax.swing.JButton listeprojets;
    // End of variables declaration//GEN-END:variables

}
